AWSTemplateFormatVersion: 2010-09-09
Description: |
  this is roman number converter project 
Parameters:
  KeyName:
    Description: Name of an existing EC2 Key Pair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 Key Pair.
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-6.1-x86_64'

Resources:
  
  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref MySecGrp
      Tags:
        - Key: Name
          Value: !Sub Emre ${AWS::StackName}
      
      UserData:
        Fn::Base64: |
          #! /bin/bash
          yum update -y
          yum install python -y  
          yum install pip -y
          pip install Flask 
          yum install wget -y
          yum install httpd -y
          wget https://raw.githubusercontent.com/Emrkts/Roman-numerals-converter/main/roman-numerals-converter-app.py
          wget -P templates https://raw.githubusercontent.com/Emrkts/Roman-numerals-converter/main/templates/index.html
          wget -P templates https://raw.githubusercontent.com/Emrkts/Roman-numerals-converter/main/templates/result.html
          sudo python3 roman-numerals-converter-app.py

  
  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSHHTTP # Required
      GroupName: emresshhttp
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyWebServer.PublicDnsName
    Description: Roman Number Application URL
